name: Weekly Anime Dataset Update

# on:
#   schedule:
#     - cron: "0 0 * * 0"   # every Sunday at 00:00 UTC
#   workflow_dispatch:       # allows manual trigger from GitHub Actions tab

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python app/update_dataset.py

      - name: Commit updated artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add artifacts/*
          git commit -m "Auto-update dataset and similarity matrix [skip ci]" || echo "No changes to commit"
          git push
