name: Weekly Dataset Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Running dataset update..."
          python app/update_dataset.py
